export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE"
export const ADD_ITEM = "ADD_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const GET_LIST_DATA = "GET_LIST_DATA"
export const GET_INIT_LIST = "GET_INIT_LIST"